#!/usr/bin/env bash
# This script installs nginx and configures it to listen on port 80
apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start
