#!/usr/bin/env bash
# This script installs nginx and configures it to listen on port 80
apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html

# redirection
sed -i '/server_name/a    return 301 http://www.google.com;
' /etc/nginx/sites-available/default

#check nginx config
nginx -t

systemctl reload nginx
