#!/usr/bin/env bash
# This script installs nginx and configures it to listen on port 80
# Create a custom error file and confirgure nginx to return the error
apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"

# create error file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# redirection
sed -i '47i\		error_page 404 /404.html;
' /etc/nginx/sites-available/default

#check nginx config
nginx -t

systemctl reload nginx
