#!/usr/bin/env bash
# A script that cofigures nginx to listen to port 80

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
