#!/usr/bin/env bash
#create a file with the scipt's id and runs an infinite loop
#script which rejects SIGTERM and SIGINT
#Deletes file created when it receives SIGQUIR or SIGTERM

ps -o pid,args -C bash | awk '/running_script/ { print $1 }' > /var/run/myscript.pid

trap 'echo "I hate the kill command"; ""' SIGTERM
trap 'echo "Y U no love me?!"; ""' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT SIGTERM
while :
do
	echo "To infinity and beyond"
done
