#!/usr/bin/env bash
#script prints numbers 1 to 100 using while loop
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5

i=1
limit=101

while [ "$i" -lt "$limit" ]
do
	if [ $((i % 3)) = 0 ] && [ $((i % 5)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
