#!/usr/bin/env bash
#script prints Best school 10 times using while loop
#prints Hi after the 9th line

i=0
limit=10

while [ "$i" -lt "$limit" ]
do
	if [ "$i" = 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
