#!/usr/bin/env bash
#script prints Best school 10 times using while loop
#prints bad luck on the 4th line and good luck on the 8th line

i=0
limit=10

while [ "$i" -lt "$limit" ]
do
	if [ "$i" = 3 ]
	then
		echo "bad luck"
	elif [ "$i" = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i + 1))
done
