#!/usr/bin/env bash
#script prints numbers 1 to 20 using while loop
#prints bad luck from China after the 4th line 
#bad luck from Japan after the 9th line
#bad luck from Italy after the 17th line

i=1
limit=21

while [ "$i" -lt "$limit" ]
do
	case $i in
		exit) break ;;
		4)
			echo "$i"
			echo "bad luck from China";;
		9)
			echo "$i"
			echo "bad luck from Japan";;
		17)
			echo "$i"
			echo "bad luck from Italy";;
		*)
			echo "$i";;
	esac
	i=$((i + 1))
done
