#!/usr/bin/env bash
#script prints numbers 1 to 20 using while loop
#prints bad luck from China after the 4th line 
#bad luck from Japan after the 9th line
#bad luck from Italy after the 17th line

i=1
limit=21

while [ "$i" -lt "$limit" ]
do
	if [ "$i" = 4 ]
	then
		echo "$i"
		echo "bad luck from China"
	elif [ "$i" = 9 ]
	then
		echo "$i"
		echo "bad luck from Japan"
	elif [ "$i" = 17 ]
	then
		echo "$i"
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	i=$((i + 1))
done
