#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

hour=0
minute=1

echo "Hour: " $hour
while [ $minute ]
do
	echo $minute
	(( minute++ ))
	if [ $minute -gt 59 ]
	then
		(( hour++ ))
		echo "Hour: " $hour
		(( minute = minute % 59 ))
	fi
	if [ $hour -gt 12 ]
	then
		break
	fi
done
