#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -lt 13 ]
do
	echo "Hour: $hour"
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
	(( minute=1 ))
done
