#!/usr/bin/env bash
#print the content of the current working directory in a list format

for file in *
do
	if [ -f "$file" ] && [ "${file:0:1}" != "." ];
       	then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
	fi
done
