#!/usr/bin/env bash
#makes nginx run as the nginx user
# Check if nginx user exists, create it if it does not
if ! id -u nginx &> /dev/null
then
    adduser --system --no-create-home --disabled-login --disabled-password --group nginx
fi

# Modify nginx configuration to run as nginx user and listen on port 8080
sed -i 's/^user .*;/user nginx;/g' /etc/nginx/nginx.conf

# Restart nginx to apply changes
nginx -s reload
